# Generated by Django 2.1.5 on 2020-02-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiclasses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
